### ISSUE TITLE
KafkaReceiver's doOnConsumer throws NullPointerException

### ISSUE THREAD

**Issue by catchin** [reactor/reactor-kafka#101]
If `doOnConsumer` is called without a `receive*` call, it throws a `NullPointerException`.
See the following example (https://gist.github.com/catchin/5f22926497392560dd90e41293dcc690):

    @ActiveProfiles("test")
    @SpringBootTest
    @EmbeddedKafka(partitions = 1, topics = ["some-topic"], controlledShutdown = true)
    class KafkaReceiverTest {
        @Autowired
        protected lateinit var kafkaProperties: KafkaProperties

        @Autowired
        protected lateinit var embeddedKafka: EmbeddedKafkaBroker

        @Test
        internal fun test_receiver() {
            val props = HashMap<String, Any>()
            props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, embeddedKafka.brokersAsString)
            props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, IntegerDeserializer::class.java)
            props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer::class.java)
            val receiverOptions = ReceiverOptions.create<String, String>(props)
                    .subscription(singletonList("some-topic"))
            KafkaReceiver.create(receiverOptions)
                    .doOnConsumer { println("I was here") }
                    .block()
        }
    }

It throws:

    java.lang.NullPointerException
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.emit(DefaultKafkaReceiver.java:408)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$doOnConsumer$8(DefaultKafkaReceiver.java:218)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.Mono.block(Mono.java:1494)
	at my.test.KafkaReceiverTest.test_receiver$test(KafkaReceiverTest.kt:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1495)
		... 52 more

So it basically tries to emit a `CUSTOM` event, but `eventSubmission` is still null.

If I add a `receive().subscribe()` on the same receiver *in front of* the `doOnConsumer` call, it works. But if I add it after the `doOnConsumer` call, it breaks again.

What would be a possible fix?

**Comment by SergeSavel** [comment]
I am having the same issue while creating consumer for fetching metadata only.
Is there a way to fetch beginning and end offsets without starting to consume real data?

**Comment by Rostom35** [comment]
Facing the same issue, I wanted to consume records with specific offsets, but `doOnConsumer` throws a `NullPointerException`

**Comment by amrynsky** [comment]
just encountered the same issue. I'm trying to read topic to the end and to do it I want to use end offsets for every partition. @SergeSavel did you find a solution for fetching metadata without starting to consume data?

**Comment by garyrussell** [comment]
You can do it with a combination of an `AdminClient` and another `Consumer`.

This is how I did it with Spring Boot (and Spring for Apache Kafka); but the same should apply here:

```java
@Bean
public ApplicationRunner runner(KafkaAdmin admin, ConsumerFactory<String, String> cf) {
	return args -> {
		Consumer<String, String> consumer = cf.createConsumer("group", "clientId", "");
		try (AdminClient client = AdminClient.create(admin.getConfig())) {
			Collection<ConsumerGroupListing> groups = client.listConsumerGroups()
					.all()
					.get(10, TimeUnit.SECONDS);
			groups.forEach(group -> {
				Map<TopicPartition, OffsetAndMetadata> map = null;
				try {
					map = client.listConsumerGroupOffsets(group.groupId())
							.partitionsToOffsetAndMetadata()
							.get(10, TimeUnit.SECONDS);
				}
				catch (InterruptedException e) {
					e.printStackTrace();
				}
				catch (ExecutionException e) {
					e.printStackTrace();
				}
				catch (TimeoutException e) {
					e.printStackTrace();
				}
				Map<TopicPartition, Long> endOffsets = consumer.endOffsets(map.keySet());
				map.forEach((tp, off) -> {
					System.out.println("group: " + group + " tp: " + tp
							+ " current offset: " + off.offset()
							+ " end offset: " + endOffsets.get(tp));
				});
			});
		}
		finally {
			consumer.close();
		}
	};
}
```

**Comment by amrynsky** [comment]
@garyrussell  thanks for the answer. The end goal is to read topic to the end and it's possible to do for non-reactive client with the code that looks like
```
// get assigned partitions
Set<TopicPartition> assignment = consumer.assignment();
// get "end" offset for every partition
Map<TopicPartition, Long> endOffsets = consumer.endOffsets(assignment);

// poll data until "end" is reached for every partition
...
```
This is what kafka connect is doing for SourceTask behind the scene to restore a state.

But what would be the right way to do it using reactive kafka api? We could access underlining consumer using `doOnConsumer` but consumer is created on demand when you start consuming data and it's not clear how to propagate this information through the reactive pipeline.

**Comment by garyrussell** [comment]
Hmmm - I would normally add a `ConsumerRebalanceListener` and use `consumer.seekToEnd(assignments)` - but I see `doOnConsumer` doesn't allow that until `receive()` has been called.

`return Mono.error(new IllegalStateException("You must call one of receive*() methods before using doOnConsumer"));`

I don't see a solution right now without making changes.

**Comment by garyrussell** [comment]
Ah - of course; the assignment won't happen until we start to `poll()` anyway so `doOnConsumer()` can be used.

**Comment by garyrussell** [comment]
Hmmm - after more thought, this won't work because `doOnConsumer()` simply schedules an event; and it won't run until the poll exits; we **must** do the seek directly within the assignment call.

**Comment by garyrussell** [comment]
Sorry for the noise - I am getting more familiar with the APIs myself - the `assignListener` will indeed work; it gets a `Consumer<Collection<ReceiverPartition>>`. `ReceiverPartition` - has `seekToEnd()` which will do the work before the poll exits.

**Comment by amrynsky** [comment]
@bsideup the current plan is to use non-reactive consumer for this. @garyrussell I tried `addAssignListener` to achieve it and it's possible to get end offsets but it had to propagate it through reactive pipeline:
```
.addAssignListener(partitions -> {
						consumer
								.doOnConsumer(consumer -> {
									Set<TopicPartition> assignment = consumer.assignment();
									return consumer.endOffsets(assignment);
								})
								.subscribe();
				})
```  
basically we need to start consuming data but somehow delay consumption until "endOffset" publisher is complete. Tried to wrap it into EmitterProcessor and use `delaySubscription` but it doesn't work.

**Comment by garyrussell** [comment]
If you just want to skip to the  end; why do you need to know the actual end offsets? `receiverPartitions.forEach(rp -> rp.seekToEnd())` will work.

**Comment by amrynsky** [comment]
@garyrussell we are trying to apply event sourcing for maintaining state. To restore state from the topic we need to read from the beginning and taking the last value for every key.

**Comment by garyrussell** [comment]
Ah - I misread your meaning - can't you just seek to beginning and just poll until you stop getting any more data?

The way we handle that in Spring is to publish a `ListenerContainerIdleEvent` after some interval passes with no new data, but you could easily start a timer when you get a message and, if that timer expires, you're done.

Or, is there some requirement to only read to the end position that was there when you started and not consume any new records added later?

**Comment by amrynsky** [comment]
@garyrussell the question here is what does it mean "stop getting any more data". We tried to wait for some time using buffer operator but this is not really correct.

Anyway, I believe I found the way to achieve what I wanted using  combination of `doOnConsumer`  and `flatMap`. There are some points for improvements but here is a code snippet with comments

```
// cache value to get metadata once
Mono<TopicPartitionMap> offsetStream = getEndOffsets().cache();

consumer
		.receive()
		// enrich stream with additional data from consumer
		.flatMap(record -> offsetStream
				.flatMap(offsets -> getPosition(record.receiverOffset().topicPartition())
										.map(position -> new TopicPartitionRecord<>(record, position, offsets))
				))
		// consume until end is reached for all partitions
		.takeUntil(record -> record.partitionMap.allSet())
		.subscribe(this::handleRecord);

private void handleRecord(TopicPartitionRecord<K, V> partitionRecord) {
	ReceiverRecord<K, V> record = partitionRecord.getRecord();
	TopicPartition topicPartition = record.receiverOffset().topicPartition();

	// need to check consumer position (not record offset)
	if (partitionRecord.consumerPosition >= partitionRecord.partitionMap.offset(topicPartition)) {
		// flag that end is reached for the corresponding partition
		partitionRecord.partitionMap.set(topicPartition);
	}
}

public Mono<Long> getPosition(TopicPartition partition) {
	return consumer
			.doOnConsumer(consumer -> consumer.position(partition));
}

public Mono<TopicPartitionMap> getEndOffsets() {
	return consumer
			.doOnConsumer(consumer -> {
				Set<TopicPartition> assignment = consumer.assignment();
				Map<TopicPartition, Long> offsets = consumer.endOffsets(assignment);
				return new TopicPartitionMap(offsets);
			});
}
```

`TopicPartitionMap` is an additional structure that helps to signal and validate end of partitions in O(1) time.

**Comment by bsideup** [comment]
Fails fast now:
https://github.com/reactor/reactor-kafka/blob/126e9a88576ebe4f3667e03baee297d23d5e6ad8/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L123

**Comment by harishvashistha** [comment]
@amrynsky this code `getPosition(record.receiverOffset().topicPartition()` is returning last offset position i.e. if my topic has 10 records in kafka then it is returning 11 everytime when this code executes.

**Comment by harishvashistha** [comment]
@amrynsky @bclozel this is the complete code, where I want to consume from kafka until end is reached for all partitions and the stop the flux, which is inspired from the code above. but this only consume first message and then stop because this code `getPosition(record.receiverOffset().topicPartition()` is returning last offset position i.e. if my topic has 10 records in kafka then it is returning value as 11 everytime when this code executes in my debug mode:

 ```
Flux<ServerSentEvent<String>> fromOffset = kafkaReceiverFromOffset.receive()
                .flatMap(record ->
                        getEndOffsets(kafkaReceiverFromOffset).cache()
                                .flatMap(offsets -> getPosition(record.receiverOffset().topicPartition(), kafkaReceiverFromOffset)
                                        .map(position -> new TopicPartitionRecord(record, position, offsets))))
                .takeUntil(TopicPartitionRecord::allSet)
                .doOnNext(r -> r.getRecord().receiverOffset().acknowledge())
                .map(receiverRecord -> {
                    try {
                        ServerSentEvent<String> serverSentEvent = ServerSentEvent.<String>builder()                               
                                .build();
                        TopicPartition topicPartition = receiverRecord.getRecord().receiverOffset().topicPartition();
                       if (receiverRecord.getPosition() >=
                                receiverRecord.getOffsets().get(topicPartition)) {
                            receiverRecord.partitionMap.add(topicPartition);
                        }
                        return serverSentEvent;
                    } catch (JsonProcessingException e) {
                        throw new RuntimeException(e);
                    }
                });
				
    public Mono<Map<TopicPartition, Long>> getEndOffsets(KafkaReceiver<String, JsonNode> kafkaReceiver) {
        return kafkaReceiver.doOnConsumer(consumer -> {
            Set<TopicPartition> assignment = consumer.assignment();
            return consumer.endOffsets(assignment);
        });
		
    public Mono<Long> getPosition(TopicPartition partition, KafkaReceiver<String, JsonNode> kafkaReceiver) {
        return kafkaReceiver
                .doOnConsumer(consumer -> {
                    Consumer<String, JsonNode> consumer1 = consumer;
                    return consumer1.position(partition);
                });
    }
	
@Getter
public class TopicPartitionRecord {
    final private ReceiverRecord<String, JsonNode> record;
    final private Long position;
    final private Map<TopicPartition, Long> offsets;
    public Set<TopicPartition> partitionMap = new HashSet<>();

    public TopicPartitionRecord(ReceiverRecord<String, JsonNode> record, Long position, Map<TopicPartition, Long> offsets) {
        this.record = record;
        this.position = position;
        this.offsets = offsets;
    }

    public boolean allSet() {
        if (partitionMap.size() == offsets.keySet().size())
            return true;
        return false;
    }
}
```


Can you help me where am I going wrong with this?
