### ISSUE TITLE
KafkaReciever unable to recover from temp network disconnect

### ISSUE THREAD

**Issue by melzayat** [reactor/reactor-kafka#131]
When a network reset (vpn disconnect and reconnect) happens during a reactive consumer consumption you see periodic attempts to connect to the kafka node, once vpn reconnects 
and the consumer rejoins the group with the last committed offset the consumer doesn't receive any messages 

A related thread that might be happening here
https://github.com/edenhill/librdkafka/issues/2363

In general how to make a reactive KafkaReceiver recover from network failures 
situation 1, 
recovering from network failure during the time before props.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, 900000); 
this is the main cause of issue
situation 2, 
assuming that situation 1 is fixed. what is the right flux pattern to
recovering from network failure after the max poll time happens and the consumer is unable to commit the offset because the partition has been reassigned in this case there should be a way to reconnect again as normally happens on restart and continue to consume 

## Expected Behavior

consumer always able to reconnect and continue consumptions
## Actual Behavior

Unable to continue receiving messages from Kafka topic

## Steps to Reproduce

I don't have a good junit example to reproduce this yet and on tight deadline posting the log info here hope that helps 

1- offset and partition info of the message received before i disconnect vpn to reproduce the problem 
```log
Received payload ='<payload here> on topic: <topic name here>, from partition: 0 with offset: **150460** at **1587212005095**'
```
2- When vpn first loses connection first message is 
```log
Then error
2020-04-18 10:11:27.290  INFO 9016 --- [UpdateConsumers] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Group coordinator <host> (id: 512519493 rack: null) is unavailable or invalid, will attempt rediscovery
2020-04-18 10:11:49.604  INFO 9016 --- [dateConsumers-1] o.a.kafka.clients.FetchSessionHandler    : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Error sending fetch request (sessionId=INVALID, epoch=INITIAL) to node 53375971: org.apache.kafka.common.errors.DisconnectException.
2020-04-18 10:11:49.709  INFO 9016 --- [dateConsumers-1] o.a.kafka.clients.FetchSessionHandler    : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Error sending fetch request (sessionId=INVALID, epoch=INITIAL) to node 1634964154: org.apache.kafka.common.errors.DisconnectException.


2020-04-18 10:11:49.739  WARN 9016 --- [dateConsumers-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Error connecting to node <host> (id: 1454665851 rack: null)
```
3- Periodic Repeating error after this while reconnecting vpn 
```log
2020-04-18 10:11:49.761  WARN 9016 --- [dateConsumers-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Error connecting to node <host> (id: 608167328 rack: null)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[na:na]
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[na:na]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[na:na]
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:104) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:403) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:363) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:151) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:943) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:474) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:212) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:249) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201) ~[kafka-clients-2.3.1.jar:na]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$PollEvent.run(DefaultKafkaReceiver.java:470) ~[reactor-kafka-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.doEvent(DefaultKafkaReceiver.java:401) ~[reactor-kafka-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$start$14(DefaultKafkaReceiver.java:335) ~[reactor-kafka-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
	at reactor.kafka.receiver.internals.KafkaSchedulers$EventScheduler.lambda$decorate$1(KafkaSchedulers.java:100) ~[reactor-kafka-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```
4- Once successfully reconnected 
```log
2020-04-18 10:12:01.667  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Discovered group coordinator <host> (id: 512519493 rack: null)
2020-04-18 10:12:01.834  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Attempt to heartbeat failed for since member id consumer-1-9f7af853-3900-4175-82b1-d73f46187e02 is not valid.
2020-04-18 10:12:01.834  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Revoking previously assigned partitions [dev-0, dev-1]
2020-04-18 10:12:01.835  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] (Re-)joining group
2020-04-18 10:12:04.967  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Successfully joined group with generation 336
2020-04-18 10:12:04.967  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Setting newly assigned partitions: dev-0, dev-1
2020-04-18 10:12:05.029  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=<groupId>] Found no committed offset for partition dev-1
2020-04-18 10:12:05.029  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=<groupId>] Setting offset for partition dev-0 to the committed offset FetchPosition{offset=**150460**, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=<host> (id: 1634964154 rack: null), epoch=-1}}
2020-04-18 10:12:05.090  INFO 9016 --- [dateConsumers-1] o.a.k.c.c.internals.SubscriptionState    : [Consumer clientId=consumer-1, groupId=metricsUpdateConsumers] Resetting offset for partition dev-1 to offset 135840.
```

5- no new messages are received 

## Your Environment

* Reactor version(s) used: 
* Other relevant libraries versions (eg. `netty`, ...):
   <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
      <exclusions>
        <exclusion>
          <groupId>io.projectreactor.netty</groupId>
          <artifactId>reactor-netty</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>0.9.6.RELEASE</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka</artifactId>
    </dependency>

    <dependency>
      <groupId>io.projectreactor.kafka</groupId>
      <artifactId>reactor-kafka</artifactId>
      <version>1.2.2.RELEASE</version>
    </dependency>

* JVM version (`javar -version`):
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
* OS and version (eg `uname -a`):
Darwin m-c02yf0sqjgh7 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

Config setup 
```java
		props.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, 900000);
		props.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, 1);
		// allows a pool of processes to divide the work of consuming and processing records
		props.put(ConsumerConfig.GROUP_ID_CONFIG, groupId);
		props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");

ReceiverOptions<String, MetricsScenarioMessage> options = ReceiverOptions
				                                                          .create(kafkaConsumerConfigurations());
		return options.commitInterval(Duration.ZERO)
		              .commitBatchSize(0)
		              .subscription(Arrays.asList(inTopicName));
```

Receiver setup 
```java
	@EventListener(CacheLoadedEvent.class)
	public void reactiveProcessScenarioMetricUpdate () {
		LOGGER.info("Starting reactive kafka consumer");
		reactiveKafkaReceiver
				.transform(this::processMessages)
				.doOnError(throwable -> LOGGER.error("Reactive Consumer Failure terminating application ....",throwable))
				.subscribe();
	}
```
```java
Flux<Void> processMessages (Flux<ReceiverRecord<String, MetricsScenarioMessage>> messages) {
		Scheduler singlerScheduler = Schedulers.newSingle("ng-met-consumer", true);
		return messages.publishOn(singlerScheduler)
		               .concatMap(record -> {service.doWork(record.value())
				                                           .publishOn(singlerScheduler)
.doFinally(signalType -> {record.receiverOffset().commit();});
})
}
```

**Comment by philaw** [comment]
Just had same issue. Looking for a solution to recover consumer.

**Comment by bsideup** [comment]
@philaw have you tried `reactor-kafka` `1.3.0.M1`?

**Comment by philaw** [comment]
> @philaw have you tried `reactor-kafka` `1.3.0.M1`?

Hi @bsideup , no we haven't upgraded to `1.3.0.M1` yet, any changes in that version would fix this issue?

We are on 1.2.2.RELEASE currently btw.

**Comment by bsideup** [comment]
@philaw 1.3.0 was heavily refactored internally and should fix a bunch of issues

**Comment by philaw** [comment]
> @philaw 1.3.0 was heavily refactored internally and should fix a bunch of issues

cool, thanks, will git it a try when got a chance.

**Comment by philaw** [comment]
Related issue: https://github.com/reactor/reactor-kafka/issues/49

**Comment by Lukoshko** [comment]
@philaw has this version fixed your problem?
