### ISSUE TITLE
Urgent -  How to dispose off subscribers from a hot flux?

### ISSUE THREAD

**Issue by arsalans** [reactor/reactor-kafka#159]
I have a war file deployed on Jboss EAP 7.0. When this Kafka receiver is created, we are not able to shutdown the jboss JVM using the stop command. As a test I commented the kafka receiver code out and created a test flux as its replacement and everything was OK.

Note, I am creating a hot flux as it will be consumed by multiple web clients.

## Expected Behavior
JBoss EAP 7.0 should shutdown without hanging.

## Actual Behavior
JBoss EAP 7.0 hangs when we issue a stop server command. It then needs to be killed.

## Steps to Reproduce
This is how I created the receiver:

```
    @Bean
    Properties vinResponseKafkaConsumerConfiguration() {

        Properties kafkaProperties = new Properties();
        kafkaProperties.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, kafkaBootstrapServers);
        kafkaProperties.put(ConsumerConfig.CLIENT_ID_CONFIG, KafkaTopicConstants.EMS_VIN_RESPONSE_CONSUMER_CLIENT_ID);
        kafkaProperties.put(ConsumerConfig.GROUP_ID_CONFIG, KafkaTopicConstants.EMS_VIN_RESPONSE_CONSUMER_GROUP_ID);
        kafkaProperties.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        kafkaProperties.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class);
        kafkaProperties.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
        return kafkaProperties;
    }

    @Bean
    ReceiverOptions<String, VinChangedEvent> vinResponseKafkaReceiverOptions() {
        JsonDeserializer<VinChangedEvent> jsonDeserializer = new JsonDeserializer<>();
        jsonDeserializer.addTrustedPackages("*");

        ReceiverOptions<String, VinChangedEvent> receiverOptions = ReceiverOptions.create(vinResponseKafkaConsumerConfiguration());
        return receiverOptions.subscription(Collections.singletonList(KafkaTopicConstants.EMS_VIN_RESPONSE_TOPIC))
                .withKeyDeserializer(new StringDeserializer())
                .withValueDeserializer(jsonDeserializer);
    }

    @Bean
    Flux<VinChangedEvent> vinChangedEventFlux(ReceiverOptions<String, VinChangedEvent> vinResponseKafkaReceiverOptions) {
        return KafkaReceiver.create(vinResponseKafkaReceiverOptions)
                .receive()
                .map(vinChangedEventReceiverRecord -> {
                    vinChangedEventReceiverRecord.receiverOffset().acknowledge();
                    return vinChangedEventReceiverRecord.value();
                })
                .log()
                .share();
    }
```

## Your Environment
Spring Boot 2.2.8.RELEASE
Red Hat JBoss EAP 7.0
reactor-kafka 1.2.2.RELEASE
Java 8
Linux 3.10

**Comment by bsideup** [comment]
You need to dispose the subscription on shutdown to terminate the threads used by the Kafka client.

**Comment by arsalans** [comment]
> You need to dispose the subscription on shutdown to terminate the threads used by the Kafka client.

So, my controller is like this, it is getting invoked straight from angular (front end):

```
    @CrossOrigin()
    @GetMapping(produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<VinChangedEvent> getVinEvents() {

        return this.vinChangedEventFlux;

}
```

How do I dispose the subscriptions?

**Comment by bsideup** [comment]
As you said, you start a hot publisher. See `ConnectableFlux` docs on how to dispose the subscriptions started by it.

**Comment by arsalans** [comment]
> As you said, you start a hot publisher. See `ConnectableFlux` docs on how to dispose the subscriptions started by it.

So, I have looked into publish/connect before, but I don't think I want to make web front end responsible to dispose off subscriptions in the back end (there are too many chances of failure as it cannot be guaranteed all the time). In that case, I was thinking if we have a timer on the server side which can dispose off subscriptions may be after some time (60 secs)?

**Comment by bsideup** [comment]
it has nothing to do with the frontend. You're using `Flux#share()` which is an alias to `publish().refCount()`.
`publish()` returns `ConnectableFlux` that you can use to control how the hot `Publisher` is created, subscribed and disposed. For example, you could use `autoConnect` with the `cancelSupport` parameter that will give you an access to `Disposable` that will terminate the subscription.

**Comment by arsalans** [comment]
@bsideup Any example code on how we use autoConnect with cancelSupport? I see its takes a Consumer?

**Comment by arsalans** [comment]
> it has nothing to do with the frontend. You're using `Flux#share()` which is an alias to `publish().refCount()`.
> `publish()` returns `ConnectableFlux` that you can use to control how the hot `Publisher` is created, subscribed and disposed. For example, you could use `autoConnect` with the `cancelSupport` parameter that will give you an access to `Disposable` that 
will terminate the subscription.

@bsideup So I tried with this, but this throws error message that "Multiple subscribers are not supported for KafkaReceiver flux" when two or more web clients call getVinEvents.

```
@CrossOrigin()
    @GetMapping(produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<VinChangedEvent> getVinEvents() {

        AtomicReference<Disposable> closeable = new AtomicReference<>();
        Flux<VinChangedEvent> hotServer = this.vinChangedEventFlux.publish().autoConnect(1, closeable::set);

        return hotServer
                .doOnSubscribe(sub -> System.out.println("client subscribe"))
                .doFinally(sig -> {
                    closeable.get().dispose();
                    System.out.println("client terminate");
                })
                .onTerminateDetach();
}


```

**Comment by arsalans** [comment]
We created a heartbeat flux and merged it with the event flux from Kafka to unsubscribe the web consumers.

**Comment by arsalans** [comment]
When we shutdown our JBOSS application server, it hangs. We created a ticket with Redhat and provided them with thread dumps when JVM is hung. They analyzed the dumps and said that that jboss threads are waiting for Kafka threads to shutdown. Here is the response from them:

From the last thread dumps, the graceful shutdown initiated, but it seems it is still waiting for some service to stop:

```
"main" #1 prio=5 os_prio=0 tid=0x00007f55ac009800 nid=0x43a3 in Object.wait() [0x00007f55b5648000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.jboss.as.server.GracefulShutdownService.awaitSuspend(GracefulShutdownService.java:86)
	- locked <0x00000005c0881bb8> (a java.lang.Object)
	at org.jboss.as.server.DomainServerMain.main(DomainServerMain.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.modules.Module.run(Module.java:329)
	at org.jboss.modules.Main.main(Main.java:507)

The http threads are idle, there are no running requests during the shutdown.

But there are some org.springframework.kafka threads running, and it seems that they are still running and do not initiate the shutdown:

"org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1" #334 prio=5 os_prio=0 tid=0x00007f5548b08800 nid=0x454d runnable [0x00007f55269e0000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000005ce2925c8> (a sun.nio.ch.Util$3)
	- locked <0x00000005ce2925b8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000005ce286d48> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.apache.kafka.common.network.Selector.select(Selector.java:794)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:539)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1281)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1225)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1159)
	at brave.kafka.clients.TracingConsumer.poll(TracingConsumer.java:89)
	at brave.kafka.clients.TracingConsumer.poll(TracingConsumer.java:83)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1071)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1027)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:958)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

ThreadPoolTaskScheduler from org.springframework is also still running: 

"ThreadPoolTaskScheduler-1" #293 prio=5 os_prio=0 tid=0x00007f556548c000 nid=0x4513 waiting on condition [0x00007f5535849000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005cada40d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

These classes are not managed by JBoss as they are not provided with JBoss. 
I would suggest to contact the development team or org.springframework.kafka.* support as these classes are not shutting down.
```

**Comment by bsideup** [comment]
@arsalans as I previously said ( https://github.com/reactor/reactor-kafka/issues/159#issuecomment-655514439 ), you need to dispose the subscription to close the consumer (will cause threads created by Kafka client to be terminated).
