### ISSUE TITLE
Using sendTransactionally makes blockhound agent throws BlockingOperationError

### ISSUE THREAD

**Issue by guillaumelamirand** [reactor/reactor-kafka#215]
Hi,

I am using reactor kafka to read and publish to kafka and when I have added reactor.blockhound agent to check any blocking call, it appears that using ` kafkaSender.sendTransactionally` is detected as doing blocking call. 

## Expected Behavior
I am thinking that the blocking call is required because of the transaction however blockhound shouldn't complain about it.

## Actual Behavior

Exception is thrown:
```
Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
Caused by: reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at org.apache.kafka.clients.producer.internals.TransactionalRequestResult.await(TransactionalRequestResult.java:69)
	at org.apache.kafka.clients.producer.KafkaProducer.initTransactions(KafkaProducer.java:599)
	at reactor.kafka.sender.internals.DefaultKafkaSender.lambda$new$0(DefaultKafkaSender.java:102)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4084)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:208)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8185)
	at reactor.core.publisher.FluxConcatMap$ConcatMapDelayed.drain(FluxConcatMap.java:805)
	at reactor.core.publisher.FluxConcatMap$ConcatMapDelayed.onNext(FluxConcatMap.java:605)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runBackfused(FluxPublishOn.java:484)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:521)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
## Steps to Reproduce

Following the sample describes here reproduce the issue : https://projectreactor.io/docs/kafka/release/reference/#transactional-sender.

Thanks

**Comment by garyrussell** [comment]
@simonbasle @bsideup - should this be moved to BlockHound to add a new `BlockHoundIntegration`?

I don't believe we can change the thread type for `SenderOptions.scheduler()` (which calls `initTransactions()`) to allow blocking calls because it is also used to publish send results.

Or, should we introduce a new thread (which allows blocking) just for this call?

There is certainly no point in proceeding if this call fails.

**Comment by simonbasle** [comment]
I _think_ we might need a new thread / separate `Scheduler`. since there's no predictability to the volume of transactions the application can attempt to init at the same time, I'd default to `Schedulers.boundedElastic()`, and document that for predictably lower volumes it might be interesting to configure a custom `Scheduler` (either bounded with lower cap, or even `Schedulers.newSingle()`).

**Comment by bsideup** [comment]
@garyrussell btw, the idea of `BlockHoundIntegration` is to let projects integrate with BlockHound without changing BlockHound's code. I thought I would mention that in case reactor-kafka eventually needs to apply some customization.

**Comment by garyrussell** [comment]
@bsideup Thanks; yes, I figured that out later, after I had written this 😄
