### ISSUE TITLE
How to create a synchronous (blocking) consumer

### ISSUE THREAD

**Issue by nishant-menon** [reactor/reactor-kafka#244]
I am trying to create a reactor-kafka consumer that has a downstream dependency on an Azure KeyVault key. The Azure KeyVault library uses a .block() in its implementation.

This is throwing the following exception: 
```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactive-kafka-ccms.ordconf.service.test-1
    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
    at reactor.core.publisher.Mono.block(Mono.java:1703)
    at com.azure.security.keyvault.keys.KeyClient.getKeyWithResponse(KeyClient.java:436)
    at com.azure.security.keyvault.keys.KeyClient.getKey(KeyClient.java:413)
    ...
    ...
```

I am creating a reactor-kafka consumer in the following way:

```
Scheduler scheduler = Schedulers.newParallel("sampleparallel");
        this.testKafkaReceiver
                .receive()
                .publishOn(scheduler)
                .groupBy(receiverRecord -> {
                    try {
                        return receiverRecord.receiverOffset().topicPartition();
                    } catch (Exception throwable) {
                        log.error("exception in groupby" + throwable);
                        return Flux.empty();
                    }
                })
                .flatMap(partitionFlux -> partitionFlux.publishOn(scheduler)
                        .map(record -> {
                            process(record).block(Duration.ofSeconds(60L));//This subscribe is to trigger processing of a message
                            return record;
                        }).concatMap(message -> {
                            log.info("Received message after processing offset:"
                                    +message.offset()+" partition: {} "+ message.partition());
                            return message.receiverOffset()
                                    .commit()
                                    .onErrorContinue((t, o) ->
                                            log.error(String.format(
                                                    "exception raised while commit offset %s", o) + t)
                                    );
                        }))
                .subscribeOn(scheduler)
                .subscribe();
```

Any recommendations on how I can do this successfully while still honoring the block() in the KeyVault library ?

TIA.

**Comment by simonbasle** [comment]
I'm guessing you're using the `KeyClient` where you should use the `KeyAsyncClient`... which has a `Mono<Response<KeyVaultKey>> getKeyWithResponse` method.

On top of that, several things jump out in your code snippet (where I see no reference to KeyVault btw):
 - `groupBy` returning `Flux.empty()` in the catch makes no sense. that said, there's no clean way of dealing with that particular case other than having a null-object `TopicPartition`
 - `map(record -> ...process(record).block())` should be turned into `concatMap(record -> process(record).thenReturn(record))`
