### ISSUE TITLE
Reactor Kafka doesn't work with latest reactor-core 3.1.6

### ISSUE THREAD

**Issue by rgeorgiev** [reactor/reactor-kafka#28]
The new reactor-core has a logic to validate blocking calls on parallel() and single() Schedulers, this leads to the below exception:
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-3
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:77)
	at reactor.core.publisher.Mono.block(Mono.java:1175)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$receiveAtmostOnce$5(DefaultKafkaReceiver.java:176)

**Comment by mayras** [comment]
Yes, same issue! Returned to 3.1.5 and it works

**Comment by smaldini** [comment]
This is a major issue to be fixed asap

**Comment by OlegDokuka** [comment]
Fixed by #35. Now should be available in the 1.0.1.BUILD-SNAPSHOT
