### ISSUE TITLE
ConcurrentModificationException in reactor-kafka 1.3.10

### ISSUE THREAD

**Issue by stroiker** [reactor/reactor-kafka#292]
Hi. I'm facing with exception from title using reactor-kafka:1.3.10 and kafka-client:3.0.0 together. Since kafka-client:3.0.0 was added multithreading check `acquireAndEnsureOpen()` in method `groupMetadata()` my application periodically began to receive ConcurrentModificationException despite there only one consumer which reads from single topic containing single partition. In debug mode I saw that `groupMetadata()` call occur and trying to acquire lock and sometimes another thread doesnt release lock yet. This behavior is reproduced on small max.poll.records size (I catched it with value == 1 and 2, and never with value == 20 and more). 
With kafka-client:2.5.0 its working great. 

Thanks for your help in advance.

**Comment by garyrussell** [comment]
Please provide a complete stack trace.

**Comment by stroiker** [comment]
`java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2464)
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2448)
	at org.apache.kafka.clients.consumer.KafkaConsumer.groupMetadata(KafkaConsumer.java:2271)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$null$13(DefaultKafkaReceiver.java:112)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503)
	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:388)
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:470)
	at reactor.core.publisher.UnicastProcessor.request(UnicastProcessor.java:546)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:447)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by garyrussell** [comment]
Can you provide a small example that exhibits this behavior? I cannot reproduce it; with my testing (with 1.3.12 and clients 3.2.2), the `groupMetadata()` call is always called on the main consumer event loop thread.

**Comment by stroiker** [comment]
Here the example on kotlin. I simplified business logic to key console output and I got exception fast enough. When Im trying to increase max.poll.records or increase "business logic" block invocation time using Thread.sleep(100) for example - it working much longer and more stable, but still getting exception

`@Configuration
class KafkaConfig {

    @Bean
    fun kafkaFlow() {
        val senderPropertiesMap = mutableMapOf<String, Any>()
        senderPropertiesMap[ProducerConfig.BOOTSTRAP_SERVERS_CONFIG] = "localhost:9092"
        senderPropertiesMap[ProducerConfig.ACKS_CONFIG] = "all"
        senderPropertiesMap[ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG] = StringSerializer::class.java
        senderPropertiesMap[ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG] = ByteArraySerializer::class.java
        senderPropertiesMap[ProducerConfig.PARTITIONER_CLASS_CONFIG] = RoundRobinPartitioner::class.java
        senderPropertiesMap[ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG] = true
        senderPropertiesMap[ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION] = 5
        senderPropertiesMap[ProducerConfig.TRANSACTIONAL_ID_CONFIG] = UUID.randomUUID().toString()
        senderPropertiesMap[ProducerConfig.TRANSACTION_TIMEOUT_CONFIG] = 60000
        senderPropertiesMap[ProducerConfig.MAX_REQUEST_SIZE_CONFIG] = 1024 * 1024
        val senderOptions = SenderOptions.create<String, ByteArray>(senderPropertiesMap)
        val sender = KafkaSender.create(senderOptions)

        val receiverPropertiesMap = mutableMapOf<String, Any>()
        receiverPropertiesMap[ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG] = "localhost:9092"
        receiverPropertiesMap[ConsumerConfig.GROUP_ID_CONFIG] = "some-consumer-group-2"
        receiverPropertiesMap[ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG] = StringDeserializer::class.java
        receiverPropertiesMap[ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG] = ByteArrayDeserializer::class.java
        receiverPropertiesMap[ConsumerConfig.AUTO_OFFSET_RESET_CONFIG] = "earliest"
        receiverPropertiesMap[ConsumerConfig.MAX_POLL_RECORDS_CONFIG] = 1
        receiverPropertiesMap[ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG] = 30000
        receiverPropertiesMap[ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG] = 10000
        receiverPropertiesMap[ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG] = 300000
        receiverPropertiesMap[ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG] = 3000
        receiverPropertiesMap[ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG] = 1048576
        receiverPropertiesMap[ConsumerConfig.PARTITION_ASSIGNMENT_STRATEGY_CONFIG] = CooperativeStickyAssignor::class.java.name
        val receiverOptions = ReceiverOptions.create<String, ByteArray>(receiverPropertiesMap)
        val bridge = KafkaReceiver.create(receiverOptions.subscription(listOf("bank_trx_success")))
            .receiveExactlyOnce(sender.transactionManager())
            .publish(1)
        bridge.concatMapDelayError<ByteArray>(
            {
                it
                    .flatMap(
                        { record ->
                            record
                                .toMono()
                                .map { println(it.key()) } // some business logic
                                .subscribeOn(Schedulers.boundedElastic())
                        }, 32
                    )
                    .then(sender.transactionManager().commit())
            },
            0
        ).subscribe()
        bridge.connect()
    }
}`
