### ISSUE TITLE
Unexpected exception with receiveAtmostOnce

### ISSUE THREAD

**Issue by vinsguru** [reactor/reactor-kafka#327]
The **_receiveAtmostOnce()_** is throwing "**_Unexpected Exception_**" every single time. I use the latest version of **_reactor-kafka_**.

```
		<dependency>
			<groupId>io.projectreactor.kafka</groupId>
			<artifactId>reactor-kafka</artifactId>
			<version>1.3.16</version>
		</dependency>
```

**_Steps:_**

1. Create a topic called "events". 
2. produce events
```
var producerConfig = Map.<String, Object>of(
        ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092",
        ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class,
        ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class
);
var options = SenderOptions.<String, String>create(producerConfig).maxInFlight(10_000);

var flux = Flux.range(1, 1_00_000)
               .map(i -> SenderRecord.create(new ProducerRecord<>("events", i.toString(), "vinsguru" + i), i.toString()));

KafkaSender.create(options)
           .send(flux)
           .doOnNext(i -> log.info("correlation id: {}", i.correlationMetadata()))
           .subscribe();
```

3. consume 
```
var consumerConfig = Map.<String, Object>of(
        ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092",
        ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class,
        ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class,
        ConsumerConfig.GROUP_ID_CONFIG, "vins-group",
        ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest",
        ConsumerConfig.GROUP_INSTANCE_ID_CONFIG, "1"
);

var options = ReceiverOptions.<String, String>create(consumerConfig)
                             .subscription(List.of("events"));

KafkaReceiver.create(options)
             .receiveAtmostOnce()
             .doOnNext(record -> log.info("key: {}, value: {}", record.key(), record.value()))
             .doOnTerminate(() -> log.info("Shutting down"))
             .subscribe();
```

It always fails with this exception

```
15:28:09.342 [reactive-kafka-vins-group-1] ERROR r.k.r.internals.ConsumerEventLoop - Unexpected exception
org.apache.kafka.common.errors.WakeupException: null
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:529)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:293)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:214)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:1169)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1506)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1453)
	at reactor.kafka.receiver.internals.ConsumerEventLoop$CommitEvent.run(ConsumerEventLoop.java:427)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
15:28:09.344 [reactive-kafka-vins-group-1] WARN  r.k.r.internals.ConsumerEventLoop - Commit failed
org.apache.kafka.common.errors.WakeupException: null
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:529)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:293)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:214)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:1169)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1506)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1453)
	at reactor.kafka.receiver.internals.ConsumerEventLoop$CommitEvent.run(ConsumerEventLoop.java:427)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
```

**Comment by oaPiet** [comment]
Hi @vinsguru, when I reproduce the issue I can see the message "Emitting 500 records, requested now 0", which indicates that the Kafka consumer is receiving a batch of 500 records, but there are currently no more records being requested by the downstream processing. This can happen when the downstream processing is slow to process the received records, leading to backpressure and the consumer being paused.

To avoid this, you can adjust the prefetch value in the receiveAtmostOnce() method to control the number of records the consumer will prefetch before waiting for downstream processing to catch up. You can experiment with different values to find the optimal balance between processing throughput and memory usage.

For example, you can set the prefetch value to 1000 as follows, and this could resolve:

```
KafkaReceiver.create(options2)
                  .receiveAtmostOnce(1000)
                  .doOnNext(record -> log.info("key: {}, value: {}", record.key(), record.value()))
                  .doOnTerminate(() -> log.info("Shutting down"))
                  .subscribe();
```

**Comment by garyrussell** [comment]
@oaPiet Thanks - yes, when back pressure is applied (and later relieved), the consumer is woken so the next poll will return immediately.

This exception should be caught and handled in the commit event.

It's not a fatal error,just log noise; the commit will be retried after the next poll.
