### ISSUE TITLE
GraalVM/native/AOT Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.serialization.StringDeserializer.<init>()

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-kafka#343]
Hello team,

I would like to reach out with an issue that is only reproducible with a native image.

I have a very simple code:

```
@Bean
    public KafkaReceiver<String, String> kafkaReceiver(final MeterRegistry registry) {
        final Map<String, Object> properties = new HashMap<>();
        properties.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServer);
        properties.put(ConsumerConfig.CLIENT_ID_CONFIG, consumerGroup);
        properties.put(ConsumerConfig.GROUP_ID_CONFIG, consumerGroup);
        properties.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, EARLIEST);
        properties.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        properties.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        final ReceiverOptions<String, String> receiverOptions = ReceiverOptions.create(properties);
        return KafkaReceiver.create(receiverOptions
                .consumerListener(new MicrometerConsumerListener(registry))
                .subscription(Collections.singleton(topicSource)));
    }
```

and a ```public void run(final String[] args) {``` which does nothing but consume messages. Nothing else.
I am using the just released SpringBoot 3.1 RC2

The code is running perfectly fine with a regular jar.
Strangely, the code is fine running as a docker image with ```org.graalvm.buildtools native-maven-plugin```

But if I am just generating the image using ```mvn -Pnative native:compile```, I am getting 100% of the time this error:

```
2023-05-08 20:56:38 38564 ERROR --- [main] [,] reactor.core.publisher.Operators : Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:830)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665)
        at reactor.kafka.receiver.internals.ConsumerFactory.createConsumer(ConsumerFactory.java:34)
        at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$withHandler$17(DefaultKafkaReceiver.java:137)
        at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72)
        at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:81)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8671)
        at reactor.core.publisher.Flux.subscribeWith(Flux.java:8792)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8637)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8561)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8479)
        at com.Myapp.run(Myapp.java:34)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)
        at com.nvidia.genesis.processing.logan.LoganApplication.main(LoganApplication.java:18)
Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.serialization.StringDeserializer
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:397)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:401)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:436)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:421)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:709)
        ... 17 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.serialization.StringDeserializer.<init>()
        at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.5/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:395)
        ... 21 common frames omitted
```

Wanted to report this issue, thank you in advance for looking into it.

**Comment by artembilan** [comment]
```
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.serialization.StringDeserializer.<init>()
```
Doesn't sound as a Reactor Kafka project issue.
What drives you to open this exactly here?

Please, consider to raise a native images resources concern exactly in Apache Kafka project.

Although I see that you already use Spring Boot, so adding `spring-kafka` into your dependencies to mitigate the problem wouldn't hurt.
That one has `KafkaRuntimeHints` impl when the mentioned `StringDeserializer` reflection info is exposed.

I'm closing this as `Won't Fix` since there is really no problem exactly in this project.
If we aim for more broader community - not just Spring users, then Apache Kafka must expose those native hints according GraalVM requirements.
