### ISSUE TITLE
reactor.kafka.receiver.internals.MockReceiverTest > consumerMethods FAILED

### ISSUE THREAD

**Issue by chemicL** [reactor/reactor-kafka#389]
In current main, when reactor-core:3.7.0-SNAPSHOT is used, the following test fails:

```
reactor.kafka.receiver.internals.MockReceiverTest > consumerMethods FAILED
    java.lang.AssertionError: VerifySubscriber timed out on reactor.core.publisher.FluxLimitRequest$FluxLimitRequestSubscriber@6d87253e
        at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
        at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.pollTaskEventOrComplete(DefaultStepVerifierBuilder.java:1728)
        at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.verify(DefaultStepVerifierBuilder.java:1298)
        at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:832)
        at reactor.kafka.receiver.internals.MockReceiverTest.verifyMessages(MockReceiverTest.java:1395)
        at reactor.kafka.receiver.internals.MockReceiverTest.receiveAndVerify(MockReceiverTest.java:1386)
        at reactor.kafka.receiver.internals.MockReceiverTest.testConsumerMethod(MockReceiverTest.java:1221)
        at reactor.kafka.receiver.internals.MockReceiverTest.consumerMethods(MockReceiverTest.java:1188)
```

**Comment by chemicL** [comment]
Resolved via #405
