### ISSUE TITLE
NoSuchMethodError in DefaultKafkaReceiver

### ISSUE THREAD

**Issue by CluEleSsUK** [reactor/reactor-kafka#66]
Getting this on startup using 1.1.0.RELEASE with the Kafka bundled with the Spring Finchley.RELEASE.
It seems that pollTimeout in PollEvent is a Duration, but my kafka client is expecting a long.

I get the following error on startup:
```
java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.Consumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
        at reactor.kafka.receiver.internals.DefaultKafkaReceiver$PollEvent.run(DefaultKafkaReceiver.java:483) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
        at reactor.kafka.receiver.internals.DefaultKafkaReceiver.doEvent(DefaultKafkaReceiver.java:414) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
        at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$start$14(DefaultKafkaReceiver.java:348) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
        at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:396) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:480) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
        at reactor.kafka.receiver.internals.KafkaSchedulers$EventScheduler.lambda$decorate$1(KafkaSchedulers.java:100) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_172]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_172]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]

```

FWIW 1.0.1.RELEASE starts fine without this error

**Comment by OlegDokuka** [comment]
@CluEleSsUK which version of Kafka client do you use in your project? Make sure the version is 2.x or higher since 1.1.x is aligned for java 8+ and apache kafka 2.x or higher
