### ISSUE TITLE
KafkaSender.onNext sometime occur CancelException

### ISSUE THREAD

**Issue by jays1204** [reactor/reactor-kafka#7]
Can I ask something?

I write kafka producer using by reactor-kafka-1.0.0.M1.

It works well normally, but sometimes occur cancelException. 
But consumer receive every message well.

So I suspect producer.send() callback closure inside of KafkaSender.onNext method.

below text is my error log.

```
ERROR KafkaSender - error {}
reactor.core.Exceptions$CancelException: The subscriber has denied dispatching

..... after approximately 1 seconds ....

ERROR RecordBatch - Error executing user-provided callback on message for topic-partition customtopicname-0:
 reactor.core.Exceptions$CancelException: The subscriber has denied dispatching
```

and my producer code.

```
ProducerRecord producerRecord = new ProducerRecord<>(topic, uid, message)
		Flux<SenderRecord<String, String>> outboundFlux = Flux.just(SenderRecord.create(producerRecord, uid))

		sender.send(outboundFlux, true)
			.doOnError(e -> {
                               log.error("[send]", e);
                        })
			.doOnNext(r -> {
                               RecordMetadata metadata = r.recordMetadata();
			log.info("[send] result - topic:${metadata.topic()}, offset:${metadata.offset()}, partition:${metadata.partition()}, meta:${r.correlationMetadata()}");
                         })
			.subscribe();
```

Should let me know why this happening? 

ps.
I am sorry about poor english sentence. I am not native english. 
if this post is not proper on this, I will delete soon.
Thank you.

**Comment by rajinisivaram** [comment]
@jays1204 Thank you for the report. This could occur if there was some other error which caused onNext to be dropped. Would it be possible to run with debug level logging?

We are hoping to release M2 soon. This fixes some of the issues in M1, so it will be good to know if the issue still occurs in M2 (we are still working on some naming issues to make the API more consistent with other reactor APIs, so it will be better to wait for M2 before changing your code).

**Comment by jays1204** [comment]
@rajinisivaram Thank you for comments. This error occurs somtimes. So I  will report debug log when I catch it. And Can I know the date when M2 release?

**Comment by rajinisivaram** [comment]
@jays1204 Thank you. M2 will be based on reactor-core 3.0.7 which is being released this week. We expect to release M2 by next week.

**Comment by jays1204** [comment]
I applied M2 to my project. Then above error not occur. So I close issue. Thnaks.

**Comment by Sage-Pierce** [comment]
I am seeing a near identical issue on M2 with `KafkaSender`

```
reactor.core.Exceptions$CancelException: The subscriber has denied dispatching
	at reactor.core.Exceptions.failWithCancel(Exceptions.java:146)
	at reactor.core.publisher.Operators.onNextDropped(Operators.java:277)
	at reactor.kafka.sender.internals.DefaultKafkaSender$AbstractSendSubscriber.checkComplete(DefaultKafkaSender.java:260)
	at reactor.kafka.sender.internals.DefaultKafkaSender$AbstractSendSubscriber.handleError(DefaultKafkaSender.java:248)
	at reactor.kafka.sender.internals.DefaultKafkaSender$AbstractSendSubscriber.lambda$onNext$0(DefaultKafkaSender.java:204)
	at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:830)
	at org.apache.kafka.clients.producer.internals.RecordBatch.done(RecordBatch.java:111)
	at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:310)
	at org.apache.kafka.clients.producer.internals.Sender.handleProduceResponse(Sender.java:270)
	at org.apache.kafka.clients.producer.internals.Sender.access$100(Sender.java:54)
	at org.apache.kafka.clients.producer.internals.Sender$1.onComplete(Sender.java:358)
	at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:96)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:368)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:225)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:126)
	at java.lang.Thread.run(Thread.java:745)
```

It only happens when I put a relatively large load on the Sender. My use-case is publishing Objects from a datastore (Dynamo DB) on to a Kafka Topic in parallel (20 threads each sending a Flux to the same `KafkaSender`.

Any ideas if there's something I can do to remedy this?

**Comment by rajinisivaram** [comment]
@Sage-Pierce This could happen if there was an error in the pipeline, causing the pipeline to be cancelled when there are responses pending from one or more sends. Can you add an `onError` immediately after your `send` to log any errors? And try running with logging enabled to see if the root cause is apparent? Thank you.

**Comment by Sage-Pierce** [comment]
@rajinisivaram Your suggestion got me pointed in the right direction. This was not an issue with Reactor/Kafka, but a threading problem with the AWS driver I was using. Adding the logging that you recommended helped me uncover a buried Exception message to that effect. Thanks for your help!
