### ISSUE TITLE
Forced commit at onPartitionsRevoked

### ISSUE THREAD

**Issue by mmaica** [reactor/reactor-kafka#80]
Scenario:
Group coordinator is suddenly unavailable or invalid, then Kafka attempts rediscovery;
Group coordinator is rediscovered;
Attempts to heartbeat fail because member ID "is not valid";
Revokes previously assigned partitions;
onPartitionsRevoked tries to commit;
a CommitFailedException is thrown.

Further details: I do not manually assign partitions and I do manual commit with 0 commit interval and 0 batch size. This means that async commits are being done.

```java
    @Override
    public void onPartitionsRevoked(Collection<TopicPartition> partitions) {
        log.debug("onPartitionsRevoked {}", partitions);
        if (!partitions.isEmpty()) {
            // It is safe to use the consumer here since we are in a poll()
            if (ackMode != AckMode.ATMOST_ONCE)
                commitEvent.runIfRequired(true);
            for (Consumer<Collection<ReceiverPartition>> onRevoke : receiverOptions.revokeListeners()) {
                onRevoke.accept(toSeekable(partitions));
            }
        }
    }
```

This method forces a commit once partitions were revoked and, in this case, Kafka just throws the error reporting that you are not supposed to commit to that partitions because it's been rebalanced. 

Maybe the solution is that the commit should always be synchronized at onPartitionsRevoked. Otherwise it may be just too late to commit.

```
2019-03-07 16:47:07.571 [kafka-coordinator-heartbeat-thread | payment-barcode-processor-success] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-2, groupId=payment-barcode-processor-success] Group coordinator localhost:9092 (id: 2147483646 rack: null) is unavailable or invalid, will attempt rediscovery
2019-03-07 16:47:29.501 [reactive-kafka-payment-barcode-processor-success-1] INFO  org.apache.kafka.clients.FetchSessionHandler - [Consumer clientId=consumer-2, groupId=payment-barcode-processor-success] Error sending fetch request (sessionId=1869284614, epoch=4633) to node 3: org.apache.kafka.common.errors.DisconnectException.
2019-03-07 16:47:29.601 [reactive-kafka-payment-barcode-processor-success-1] INFO  org.apache.kafka.clients.FetchSessionHandler - [Consumer clientId=consumer-2, groupId=payment-barcode-processor-success] Error sending fetch request (sessionId=1543593378, epoch=4630) to node 1: org.apache.kafka.common.errors.DisconnectException.
2019-03-07 16:47:38.327 [reactive-kafka-payment-barcode-processor-success-1] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-2, groupId=payment-barcode-processor-success] Discovered group coordinator localhost:9092 (id: 2147483646 rack: null)
2019-03-07 16:47:41.528 [reactive-kafka-payment-barcode-processor-success-1] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-2, groupId=payment-barcode-processor-success] Attempt to heartbeat failed for since member id consumer-2-829315bd-9759-4b12-b114-7e3b8ba01c26 is not valid.
2019-03-07 16:47:41.529 [reactive-kafka-payment-barcode-processor-success-1] INFO  org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-2, groupId=payment-barcode-processor-success] Revoking previously assigned partitions [payment-barcode-legacy-digital-result-v1-3, payment-barcode-legacy-digital-result-v1-4]
2019-03-07 16:47:41.530 [reactive-kafka-payment-barcode-processor-success-1] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-2, groupId=payment-barcode-processor-success] (Re-)joining group
2019-03-07 16:47:41.545 [reactive-kafka-payment-barcode-processor-success-1] WARN  reactor.kafka.receiver.internals.DefaultKafkaReceiver - Commit failed
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:798) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.doCommitOffsetsAsync(ConsumerCoordinator.java:631) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsAsync(ConsumerCoordinator.java:598) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitAsync(KafkaConsumer.java:1486) ~[kafka-clients-2.0.0.jar!/:na]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$CommitEvent.run(DefaultKafkaReceiver.java:541) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$CommitEvent.runIfRequired(DefaultKafkaReceiver.java:569) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.onPartitionsRevoked(DefaultKafkaReceiver.java:239) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinPrepare(ConsumerCoordinator.java:465) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:408) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:333) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) ~[kafka-clients-2.0.0.jar!/:na]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$PollEvent.run(DefaultKafkaReceiver.java:483) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.doEvent(DefaultKafkaReceiver.java:414) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$start$14(DefaultKafkaReceiver.java:348) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.kafka.receiver.internals.KafkaSchedulers$EventScheduler.lambda$decorate$1(KafkaSchedulers.java:100) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2019-03-07 16:47:41.546 [reactive-kafka-payment-barcode-processor-success-1] ERROR reactor.kafka.receiver.internals.DefaultKafkaReceiver - Consumer flux exception
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:798) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.doCommitOffsetsAsync(ConsumerCoordinator.java:631) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsAsync(ConsumerCoordinator.java:598) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitAsync(KafkaConsumer.java:1486) ~[kafka-clients-2.0.0.jar!/:na]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$CommitEvent.run(DefaultKafkaReceiver.java:541) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$CommitEvent.runIfRequired(DefaultKafkaReceiver.java:569) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.onPartitionsRevoked(DefaultKafkaReceiver.java:239) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinPrepare(ConsumerCoordinator.java:465) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:408) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:333) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175) ~[kafka-clients-2.0.0.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) ~[kafka-clients-2.0.0.jar!/:na]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$PollEvent.run(DefaultKafkaReceiver.java:483) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.doEvent(DefaultKafkaReceiver.java:414) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$start$14(DefaultKafkaReceiver.java:348) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.kafka.receiver.internals.KafkaSchedulers$EventScheduler.lambda$decorate$1(KafkaSchedulers.java:100) ~[reactor-kafka-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.2.2.RELEASE.jar!/:3.2.2.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by haigopi** [comment]
Also observed that, after the CommitFailedException, that consumer is not consuming any more message from the newly assigned partitions.

**Comment by sarialem** [comment]
This is also happening in a k8s environment where we have autoscaling that triggers a rebalance, where we see the same behaviour, any workaround or planned fix?

**Comment by sarialem** [comment]
I just tested code on master (coming in 1.3.0 release), and just doing a `retry()` or `retryWhen()` when it's CommitFailedException, and it continues functioning properly after partitions re-assignment.

**Comment by sarialem** [comment]
> Also observed that, after the CommitFailedException, that consumer is not consuming any more message from the newly assigned partitions.

This can be fixed by workarounds suggested here: https://github.com/reactor/reactor-kafka/issues/19

**Comment by bsideup** [comment]
`1.3.0.RELEASE` is released now 👍
