### ISSUE TITLE
Client cannot handle error scenarios when connection to broker is lost

### ISSUE THREAD

**Issue by yevtsy** [reactor/reactor-kafka#90]
As a result of the investigation https://github.com/reactor/reactor-kafka/issues/70#issuecomment-483623412 I found out client cannot handle errors in this case.

**Steps to reproduce:**
1. Minor change to [project](https://github.com/malinovskiy-alex/proxy/):
```java
return sender.send(Mono.just(SenderRecord.create(new ProducerRecord<>(topicName, null, message), message)))
            .doOnNext(next -> System.out.println("next: " + next))
            .doOnError(error -> System.out.println("error -> " + error))
            .flatMap(result -> {
            ....
```
so, we added logs to track next/error events
2. Run application, turn off Kafka broker, send request
3. After exception `org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for users-0:120001 ms has passed since batch creation` there are no events in `.doOnError(...)` handler
(also you can see in debug logs that record was expired and no notification to client wasn't sent)

**Expected behavior:** 
Similarly to [kafka client send with callback](https://kafka.apache.org/22/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html#send-org.apache.kafka.clients.producer.ProducerRecord-org.apache.kafka.clients.producer.Callback-) I want to have the possibility to handle errors

**Comment by youagree** [comment]
maybe somebody know about alternative solution for this problem?

**Comment by guillaumelamirand** [comment]
Hello,

I am facing same issue when a consumer keeps retrying for ever with warn log : 

`17:17:08.509 [reactive-kafka-dee312c1-a488-48ee-a312-c1a488f8ee35-1] [] WARN  o.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-dee312c1-a488-48ee-a312-c1a488f8ee35-1, groupId=dee312c1-a488-48ee-a312-c1a488f8ee35] Connection to node -1 (localhost/127.0.0.1:9096) could not be established. Broker may not be available.
17:17:08.509 [reactive-kafka-dee312c1-a488-48ee-a312-c1a488f8ee35-1] [] WARN  o.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-dee312c1-a488-48ee-a312-c1a488f8ee35-1, groupId=dee312c1-a488-48ee-a312-c1a488f8ee35] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected`

I was expecting to be able to control this behaviour or catch the error signal or anything. Does someone have an idea to deal with it?
Thanks

**Comment by garyrussell** [comment]
Unfortunately, the `kafka-clients` provides no indication of the broker being down; the `poll()` simply returns with no records and no exception is thrown.

You could monitor the cluster state with some other mechanism (e.g. `AdminClient.describeCluster()`) in some other thread or via JMX.

**Comment by guillaumelamirand** [comment]
Thank you for the answer. Do you have in mind a way to link consumer
subscription to cluster state ?

Le jeu. 3 nov. 2022 à 17:37, Gary Russell ***@***.***> a
écrit :

**Comment by garyrussell** [comment]
No; sorry - another option might be `doOnConsumer()` to get the `metrics`. There is a metric...

    connection-count:The current number of active connections.

...which might help.

**Comment by guillaumelamirand** [comment]
Just to give you some up. I figured out a way to check connection status checking the metric you mentioned periodically using doOnConsumer and doOnSubscribe, so thank you very much for the insight.

**Comment by yusiwen** [comment]
@guillaumelamirand I'm facing the same problem here. When I turn off kafka broker, it keeps reconnecting every second. I just want it to fail fast. How did you fix this? Can you give me some advice? thanks

**Comment by guillaumelamirand** [comment]
hi @yusiwen 

I have implemented a mechanism as suggested by @garyrussell based on doOnConsumer and metrics.
Basically, I am storing a reference to the current consumer. Then I loop every `RECONNECT_ATTEMPT * RECONNECT_BACKOFF_MS` ms and check if the number of connection-close-total is higher than 0 when connection-count equals 0.

**Comment by yusiwen** [comment]
@garyrussell Thanks for your reply!

So, I'm supposed to check broker connections on `KafkaReceiver` (`doOnConsumer` is a method of `KafkaReceiver`) , assuming that `KafkaSender` is using the same brokers as receiver, am I right? If the check failed, so next time before `KafkaSender.send()` is going to be called, I can skip the call and return a failure directly to client.

Unfortunately, even if I'm right, I'm still wondering how to use `doOnConsumer` and how to get metrics? I'm new to reactor-kafka and really confused now.

Can you give me more details about them, some sample code or article links would be appreciated, thanks a lot and best wishes

**Comment by guillaumelamirand** [comment]
Indeed `doOnConsumer` is for `KafkaReceiver`, while `doOnProducer` is for `KafkaSender`. In both cases, you will have access to the underlying metrics allowing you to check if there are any failure connections. 

Here some extract of the solution: 

- The following is used to store reference to the underlying consumer

```
public static <K, V> Function<Flux<ConsumerRecord<K, V>>, Publisher<ConsumerRecord<K, V>>> transform(....) {
        return consumerRecordFlux -> {
            AtomicReference<Consumer<K, V>> consumerRef = new AtomicReference<>();
            Sinks.Many<ConsumerRecord<K, V>> kafkaErrorSink = Sinks.many().unicast().onBackpressureError();
            return consumerRecordFlux
                .zipWith(storeConsumerReference(qosStrategy, consumerRef), (c, o) -> c)
                .materialize()
                .mergeWith(kafkaErrorSink.asFlux().materialize())
                .<ConsumerRecord<K, V>>dematerialize()
                .doOnSubscribe(subscription -> handleKafkaDisconnection(consumerRef, kafkaErrorSink));
        };
    }
```

- you can use it like this
```
kafkaReceiver.receive()
                                        .transform(KafkaReceiverErrorTransformer.transform(...))
```

- then the following code is the loop used to check the metrics :

```
private static <K, V> void handleKafkaDisconnection(
        final AtomicReference<Consumer<K, V>> consumerRef,
        final Sinks.Many<ConsumerRecord<K, V>> kafkaErrorSink
    ) {
        Flux
            .interval(Duration.ofMillis(KAFKA_CONNECTION_CHECK_INTERVAL))
            .publishOn(Schedulers.boundedElastic())
            .doOnNext(interval -> {
                Consumer<K, V> consumer = consumerRef.get();
                if (consumer != null) {
                    mayThrowConnectionClosedException(kafkaErrorSink, consumer.metrics());
                }
            })
            .retryWhen(Retry.indefinitely().filter(throwable -> !(throwable instanceof KafkaConnectionClosedException)))
            .subscribe(
                interval -> log.debug("Kafka endpoint connection validated."),
                throwable -> log.warn("Kafka endpoint connector disconnected.")
            );
    }
```

- then the following is how the metrics are checked 
```
protected static <T> void mayThrowConnectionClosedException(
        final Sinks.Many<T> kafkaErrorSink,
        final Map<MetricName, ? extends Metric> metrics
    ) {
        Double connectionCount = null;
        Double connectionCloseTotal = null;
        for (Metric metric : metrics.values()) {
            if (metric.metricValue() != null) {
                if (metric.metricName().name().equals("connection-count")) {
                    connectionCount = Double.parseDouble(metric.metricValue().toString());
                } else if (metric.metricName().name().equals("connection-close-total")) {
                    connectionCloseTotal = Double.parseDouble(metric.metricValue().toString());
                }
                if (connectionCount != null && connectionCloseTotal != null) {
                    break;
                }
            }
        }
        if (connectionCloseTotal != null && connectionCloseTotal > 0 && connectionCount != null && connectionCount == 0) {
            kafkaErrorSink.tryEmitError(new KafkaConnectionClosedException());
            throw new KafkaConnectionClosedException();
        }
    }
```

I hope this will help.

**Comment by yusiwen** [comment]
@guillaumelamirand Thanks! You're my savior! I‘ll try it right away.

**Comment by yusiwen** [comment]
@garyrussell I've managed to make the code running. After started, `connection-count` was `3`, then I unplugged the wire cable of my PC. `KafkaConsumer` started throwing exceptions, but the `connection-count` was still `1`, not zero. I waited for about 30 minutes, it's still `1`, and `connection-close-total` is `2`.
Is this the expected scenario? How should I check the metrics correctly?

Thanks

p.s I'm using reactor-kafka 1.3.17

**Comment by yusiwen** [comment]
@guillaumelamirand 
This is my config for KafkaReceiver

```java
        consumerProps.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, brokers);
        consumerProps.put(ConsumerConfig.GROUP_ID_CONFIG, groupId);
        consumerProps.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, autoOffsetReset); // earliest
        consumerProps.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, autoCommit); // false
        consumerProps.put(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, 10000);
        consumerProps.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        consumerProps.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);

        return ReceiverOptions.<String, String>create(consumerProps).subscription(Collections.singleton(topic));
```
My checking interval is also 10000ms. Still, after wating about 30 mins, there is still 1 connection remains, below is the log output:

```text
2023-04-04 10:46:02.903 DEBUG 102846 --- [oundedElastic-1] c.c.p.f.service.KafkaReceiverService     : Checking 'connection-close-total'...2.0
2023-04-04 10:46:02.903 DEBUG 102846 --- [oundedElastic-1] c.c.p.f.service.KafkaReceiverService     : Checking 'connection-count'...1.0
2023-04-04 10:46:02.903 DEBUG 102846 --- [oundedElastic-1] c.c.p.f.service.KafkaReceiverService     : Kafka endpoint connection validated.
2023-04-04 10:46:03.813  WARN 102846 --- [u-message-group] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-fsu-message-group-1, groupId=fsu-message-group] Error connecting to node 172.16.62.219:9092 (id: 1 rack: null)

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
```

Is something wrong with my config?
